### PR TITLE
feat(plotly): Bump plotly from 1.25.0 to 1.41.1

### LINKED ISSUE #5: Upgrade to latest version of plotly
As surfaced in https://github.com/nteract/nteract/issues/3323, we need to upgrade our plotly. :)

### PR DESCRIPTION
**Pull request by alexandercbooth**
Closes #5.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Fantastic, thank you!

**Comment by rgbkrk** [comment]
Want to ship it too? If it's your first time publishing on npm, I can walk you through it.

**Comment by alexandercbooth** [comment]
Sure, I can do that 👍.  I haven't shipped anything using `semantic-release` specifically, but I have published `ion` and `create-nteract-app` to npm.

It seems like travis is setup to run the [semantic-release script](https://github.com/nteract/minimal-plotly/blob/master/.travis.yml#L13) for us, but how do we trigger travis to do that? I would have expected it to happen once a commit is made to master (like the merging of this PR), but it doesn't seem like that happened.

Or should I instead just run `npm run semantic-release` from master on my machine and skip travis altogether?

**Comment by rgbkrk** [comment]
You know, I'm not sure. @lgeiger set this up.

**Comment by lgeiger** [comment]
Looks like the automatically publishing is failing https://travis-ci.org/nteract/minimal-plotly/builds/430590821#L1727

**Comment by lgeiger** [comment]
Probably due to the semantic release upgrade: https://github.com/nteract/minimal-plotly/pull/6/commits/025bc1269b37726145d5971196f7a9e33f6bc171

**Comment by lgeiger** [comment]
I can setup a new auto-publishing tomorrow, or we can switch back to manual publishing and rip out semantic-release.

**Comment by jameskoch** [comment]
@lgeiger Any chance you have time to setup the auto-publish?

**Pull request merged**
